name: E2E Tests (k3s)

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
      - k8s-coverage
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

concurrency:
  group: k3s

jobs:
  k3s:
    name: "k3s (experimental)"
    runs-on: ubuntu-22.04
    # NOTE: Just a thought in case the timeouts fail; might not be
    # necessary, but might not hurt either, would vary based on the
    # size of the testing matrix, too.
    timeout-minutes: 120
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        # TODO: Document which versions we support and cover them.
        # https://github.com/StackStorm/stackstorm-k8s/issues/342
        k3s-channel:
          - "v1.24.9+k3s1"
          - "v1.25.5+k3s1"
          - "v1.26.0+k3s1"
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up K3s
        id: k3s
        uses: jupyterhub/action-k3s-helm@v3
        with:
          k3s-channel: ${{ matrix.k3s-channel }}

      - name: Update stackstorm-ha chart dependencies
        run: |
          helm dependency update

      - name: Helm install
        run: |
          helm install --timeout 15m0s --debug --wait \
            --name-template stackstorm-ha .

      - name: Helm test
        run: |
          helm test stackstorm-ha

      - name: Helm upgrade with RBAC enabled
        run: |
          helm upgrade --set st2.rbac.enabled=true \
            --timeout 5m0s --debug --wait stackstorm-ha .

      - name: Helm test
        run: |
          helm test stackstorm-ha

      - name: Show all Kubernetes resources
        if: ${{ always() }}
        run: |
          kubectl get all
